# fly.toml app configuration file generated for timetrack-2whuug on 2025-07-01T09:27:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timetrack-2whuug'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
