app = "timetrack"
primary_region = "iad"

[build]

[env]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "timetrack_data"
  destination = "/app/instance"

[processes]
  app = "flask run --host=0.0.0.0"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256