"""-m

Revision ID: 272e765b4ea4
Revises: c72667903a91
Create Date: 2025-07-10 11:47:00.670322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272e765b4ea4'
down_revision = 'c72667903a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the billingtype enum first
    billingtype_enum = sa.Enum('NON_BILLABLE', 'HOURLY', 'FIXED_RATE', name='billingtype')
    billingtype_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('report_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('component_config', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_export_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['saved_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_team_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('shared_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['saved_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shared_with_team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company_settings', sa.Column('default_currency', sa.String(length=3), nullable=True))
    op.add_column('project', sa.Column('billing_type', sa.Enum('NON_BILLABLE', 'HOURLY', 'FIXED_RATE', name='billingtype'), nullable=False, server_default='NON_BILLABLE'))
    op.add_column('project', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('project', sa.Column('billing_notes', sa.Text(), nullable=True))
    op.add_column('time_entry', sa.Column('is_billable', sa.Boolean(), nullable=True))
    op.add_column('time_entry', sa.Column('billing_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('time_entry', sa.Column('billing_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entry', 'billing_amount')
    op.drop_column('time_entry', 'billing_rate')
    op.drop_column('time_entry', 'is_billable')
    op.drop_column('project', 'billing_notes')
    op.drop_column('project', 'hourly_rate')
    op.drop_column('project', 'billing_type')
    op.drop_column('company_settings', 'default_currency')
    op.drop_table('report_shares')
    op.drop_table('report_export_history')
    op.drop_table('saved_reports')
    op.drop_table('report_templates')
    op.drop_table('report_components')
    
    # Drop the billingtype enum
    billingtype_enum = sa.Enum('NON_BILLABLE', 'HOURLY', 'FIXED_RATE', name='billingtype')
    billingtype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
